[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "densidade_e_economia"
version = "0.0.1"
description = "Uma an\u00e1lise e predi\u00e7\u00e3o sobre a densidade populacional e econ\u00f4mica chinesa utilizando t\u00e9cnicas de an\u00e1lise descritiva e machine learning."
authors = [
  { name = "Cleber_Santos" },
]
license = { file = "LICENSE" }
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License"
]
requires-python = "~=3.10.0"


[tool.ruff]
line-length = 99
src = ["densidade_e_economia"]
include = ["pyproject.toml", "densidade_e_economia/**/*.py"]

[tool.ruff.lint]
extend-select = ["I"]  # Add import sorting

[tool.ruff.lint.isort]
known-first-party = ["densidade_e_economia"]
force-sort-within-sections = true

